### PR TITLE
Decimal type and Project Benchmarks added

### PR DESCRIPTION
**Pull request by hugobritobh**
Project Benchmarks added (with BenchmarkDotNet)

Contains for AttributeSyntax. Example: [assembly: JsonSrcGen.JsonArray(typeof(int))]

Is Number: Details in [BenchmarksNumber](https://github.com/hugobritobh/BenchmarksNumber)

Update packages
Microsoft.CodeAnalysis.Analyzers (3.3.1)
Microsoft.NET.Test.Sdk (16.8.0)
NUnit3TestAdapter" Version (3.17.0)

Unit Tests
Outcomes
347 Passed
4 Failed (It seems that an error occurred just for me, so it could be a time zone)
Do some testing with internationalization (Example: DecimalPropertyTests)

### CODE REVIEW

**Comment by trampster** [comment]
I think I may have found an even faster is number method.

if((value - '0') <= 9)

**Comment by hugobritobh** [comment]
I put the new results: [BenchmarksNumber](https://github.com/hugobritobh/BenchmarksNumber)

However, you could accept this version and when uploading the structure version by reference I changed the number verification to the "new method"

**Comment by trampster** [comment]
Sorry I deleted my comment because the number subtraction method doesn't actually work :(

**Comment by trampster** [comment]
You have left some commented code in your benchmarks. Please remove those.

**Pull request closed without merging**
